import { runWebAutomationPrompt } from './web-automation.js';

const CLAUDE_WEB_CONFIG = {
  providerLabel: 'Claude',
  scope: 'ClaudeWebAutomation',
  defaultTargetUrl: 'https://claude.ai/new?incognito',
  popupWidth: 980,
  popupHeight: 900,
  popupTop: 40,
  popupLeft: 40,
  responseTimeoutMs: 600000,
  responseIdleTimeoutMs: 600000,
  responseFirstTokenTimeoutMs: 600000,
  urlMatchers: ['https://claude.ai/'],
  inputSelectors: [
    '#main-content [contenteditable="true"][role="textbox"]',
    '#main-content [contenteditable="true"]',
    '#main-content textarea',
    'div[contenteditable="true"][role="textbox"]',
    'div[contenteditable="true"].ProseMirror',
    'div.ProseMirror[contenteditable="true"]',
    'textarea[placeholder*="Message"]',
    'textarea[placeholder*="Talk"]',
    'form [contenteditable="true"]',
    'form textarea',
  ],
  sendButtonSelectors: [
    'button[aria-label*="Send"]',
    'button[data-testid*="send"]',
    'form button[type="submit"]',
    'button[type="submit"]',
  ],
  stopButtonSelectors: [
    'button[aria-label*="Stop"]',
    'button[data-testid*="stop"]',
  ],
  responseBusySelectors: [
    // Only explicit "actively streaming" states. Bare-presence matches like
    // [data-is-streaming] (matches data-is-streaming="false") and broad
    // [data-testid*="stream"]/"typing" could latch "busy" forever and block
    // completion, so they are intentionally excluded.
    '#main-content [data-is-streaming="true"]',
    '#main-content [aria-busy="true"]',
    'main [data-is-streaming="true"]',
    'main [aria-busy="true"]',
  ],
  responseSettleDelayMs: 2200,
  primaryAssistantTextSelectors: [
    '#main-content .font-claude-response .standard-markdown',
    '#main-content .font-claude-response .progressive-markdown',
    '#main-content .font-claude-response',
    '#main-content .overflow-x-auto > pre > code',
    '#main-content pre code',
    '[data-testid*="assistant"] pre code',
    '[data-testid*="message"] pre code',
    '[data-testid*="chat-message"] pre code',
    'main pre code',
  ],
  assistantTextSelectors: [
    '#main-content .font-claude-response .standard-markdown',
    '#main-content .font-claude-response .progressive-markdown',
    '#main-content .font-claude-response',
    '#main-content .standard-markdown',
    '#main-content .progressive-markdown',
    '#main-content pre code',
    '#main-content .overflow-x-auto > pre > code',
    '#main-content [data-is-streaming]',
    '#main-content .whitespace-pre-wrap',
    '#main-content .font-claude-message',
    '#main-content .prose',
    '[data-testid*="assistant"] .font-claude-message',
    '[data-testid*="assistant"] [data-is-streaming]',
    '[data-testid*="assistant"] pre code',
    '[data-testid*="message"] .font-claude-message',
    '[data-testid*="message"] .prose',
    '[data-testid*="message"] pre code',
    '[data-testid*="chat-message"] .font-claude-message',
    '[data-testid*="chat-message"] pre code',
    'main .font-claude-message',
    'main .prose',
    'main pre code',
  ],
  assistantTurnContainerSelectors: [
    '#main-content [data-test-render-count]',
    '#main-content [data-message-id]',
    '#main-content [data-testid*="message"]',
  ],
  assistantTurnRoleHeadingSelectors: ['h2.sr-only'],
  assistantTurnRoleHeadingPattern: '^Claude responded:',
  assistantContentSelectors: [
    '.font-claude-response .standard-markdown',
    '.font-claude-response .progressive-markdown',
    '.font-claude-response',
    '.standard-markdown',
    '.progressive-markdown',
  ],
  loginSelectors: [
    'a[href*="/login"]',
    'button[aria-label*="Log in"]',
    'button[aria-label*="Sign in"]',
    'input[type="email"]',
  ],
  authRequiredMessage: 'Please log into Claude in a normal browser tab first.',
  openPopupMessage: 'Opening Claude popup.',
  popupCreatedMessage: 'Claude popup created.',
  waitForTabMessage: 'Waiting for Claude tab to finish loading.',
  tabReadyMessage: 'Claude tab ready.',
  waitForHydrationMessage: 'Waiting for Claude page hydration.',
  injectRunnerMessage: 'Injecting Claude prompt runner.',
  progressMessage: 'Claude prompt runner in progress.',
  retryMessage: 'Retrying prompt after submit-start failure.',
  partialSuccessMessage: 'Using parseable partial Claude response after timeout.',
  partialRetrySuccessMessage: 'Using parseable partial Claude response after retry timeout.',
};

export async function runClaudeWebPrompt(prompt, options = {}) {
  const targetUrl = options.profile?.targetUrl || options.targetUrl || CLAUDE_WEB_CONFIG.defaultTargetUrl;
  return runWebAutomationPrompt(prompt, CLAUDE_WEB_CONFIG, {
    ...options,
    targetUrl,
  });
}
